### ISSUE TITLE
qmake ставит winewizard в /usr вместо /usr/bin

### ISSUE THREAD

**Issue by suhr** [LLIAKAJL/WineWizard#11]

**Comment by LLIAKAJL** [comment]
Так, странный баг. В файле .pro есть такие строки:

TARGET = winewizard
isEmpty(PREFIX) {
 PREFIX = /usr/bin
}
target.path = $$PREFIX/

Получается, у вас переменная PREFIX не пуста, если не ставит по умолчанию? Или в новом qmake как-то по другому задается?

**Comment by suhr** [comment]
Префикс — не BINDIR же. В норме, бинарники должны идти в `$PREFIX/bin`, остальное — в `$PREFIX/share`. Сейчас же бинарники ставятся в `$PREFIX`, а `/usr/share` вообще прибито гвоздями.

(кстати, по умолчанию make должен ставить всё в /usr/local/, так как его можно потом снести без боли)

**Comment by suhr** [comment]
https://github.com/wereturtle/ghostwriter/blob/master/ghostwriter.pro#L233

Вот так было бы лучше.

**Comment by LLIAKAJL** [comment]
Насчет PREFIX ты прав, косяк. А вот насчет /usr/local - не уверен, т.к. у меня он пуст и никогда в него ничего не ставилось. Я конечно make ничего уже давно не ставил, только checkinstall, но когда-то один раз так систему убил. Так вот, я не припоминаю, чтобы тогда что-то туда ставилось по умолчанию.

**Comment by suhr** [comment]
> у меня он пуст и никогда в него ничего не ставилось

Собственно, именно поэтому он и используется всюду по умолчанию. В `/usr` ставить можно только под бдительным надзором пакетного менеджера.

**Comment by LLIAKAJL** [comment]
mkdir: невозможно создать каталог «/usr/local/share/icons»: Нет такого файла или каталога

Checkinstall не хочет туда ставить иконки.

**Comment by suhr** [comment]
Для checkinstall как раз стоит поставить префикс /usr.

**Comment by LLIAKAJL** [comment]
Т.е. самому указывать префикс при запуске checkinstall?

**Comment by suhr** [comment]
Да.

**Comment by LLIAKAJL** [comment]
Еще вопрос - из /usr/local можно просто удалять руками?

**Comment by suhr** [comment]
Да.

**Comment by LLIAKAJL** [comment]
Готово. Только что теперь с релизом делать? Новый выпускать? Тогда версию в репозитории придется менять. Не выпускать релиз? Посоветуешь что-нибудь?

**Comment by suhr** [comment]
Я бы поднял версию до 2.0.2, если никаких проблем нет.

**Comment by LLIAKAJL** [comment]
Проблема есть, т.к. нужно будет сменить версию в репозитории самого Wine Wizard, из которого скрипты берутся и обновления смотрятся. Всем, у кого он уже стоит придется все переустановить, хотя причин именно для них нет.

**Comment by LLIAKAJL** [comment]
К тому же, сейчас еще выбор языка по локали добавлю - опять релиз новый?

**Comment by suhr** [comment]
> Всем, у кого он уже стоит придется все переустановить

Семантическое версионирование Wine Wizard не умеет что-ли?

> К тому же, сейчас еще выбор языка по локали добавлю - опять релиз новый?

Ну это как сам хочешь.

**Comment by LLIAKAJL** [comment]
На данный момент не умеет, но это идея! Как сразу не додумался? Спасибо!
