### ISSUE TITLE
Не спрашивать о выходе

### ISSUE THREAD

**Issue by suhr** [LLIAKAJL/WineWizard#14]
[![](https://cloud.githubusercontent.com/assets/65870/16664917/5b0ffd64-4493-11e6-845e-6c1b63f6c7a3.png)](https://goodui.org/#8)

Надоедливые вопросы — моветон, бессмысленные надоедливые вопросы — вдвойне моветон.

**Comment by LLIAKAJL** [comment]
Не в нашем случае. Win-приложения ведут себя непредсказуемо, могут перекрыть экран, начнешь Esc нажимать - закроешь Wine Wizard, а тебе надо до Terminate добраться. Он, конечно, и при выходе все терминирует, но это не совсем правильно.

**Comment by suhr** [comment]
А зачем он спрашивает даже тогда, когда ни одного приложения не запущено? Да, и по Esc он всё равно в трей сворачивается.

**Comment by LLIAKAJL** [comment]
В трей он сворачивает, если автозавершение не включено(удобная, кстати, штука), если включено - выйдет. Вообще, это дело вкуса. Я знаю, что в GNOME не спрашивают почти никогда и ни о чем, но это одна из причин, почему я им не пользуюсь. В KDE спрашивают при любой мелочи, и я к этому привык, и на самом деле мне не нравится, когда приложение считает что оно умнее меня и знает, что я хотел сделать. Я ведь мог просто промахнуться мимо кнопки или нажать Ctrl+Q случайно. Так что вот так.

**Comment by LLIAKAJL** [comment]
Может тогда галку в настройках добавить, спрашивать ли при выходе?

**Comment by suhr** [comment]
Можно. Хотя, вопрос о том, каким должен быть дефолт, остаётся.

**Comment by LLIAKAJL** [comment]
Дефолт, как мне кажется, должен быть всегда и в любой программе максимально строгим, чтобы неопытный пользователь ничего не натворил, а опытный все настроил под себя. Поэтому в данном случае лучше спрашивать по умолчанию. Все таки обиднее, когда тебя не спросили и закрыли, чем спросили лишний раз.

**Comment by suhr** [comment]
Закрытую программу можно просто снова открыть, проблема есть только если какие-то процессы ещё запущены. Тогда стоит спрашивать не выйти ли, а убить ли процессы или продолжить.

> Дефолт, как мне кажется, должен быть всегда и в любой программе максимально строгим, чтобы неопытный пользователь ничего не натворил, а опытный все настроил под себя.

Неопытный не значит глупый. Защита нужна там, где можно поранится, в остальных случаях программе следует доверять пользователю и понимать его с полуслова.

Да и без автозакрытия программу можно закрыть только намерянно.

**Comment by LLIAKAJL** [comment]
> Закрытую программу можно просто снова открыть

Это смотря, откуда он ее запускал. Может ему для этого пришлось в меню лезть, искать ее и т.д. А закрыть может и ненамеренно, промахнувшись мимо кнопки "Настройки", т.к. они рядом. Может он пьяный, в конце концов :) И он это будет делать много раз, пока не додумается включить спрашивание.

**Comment by LLIAKAJL** [comment]
Вообще, проблема надуманная, и решить ее однозначно не получится, т.к. не спрашивать - нестандартно в кедах, спрашивать - в гноме. Палка о двух концах. Поэтому, пусть будет спрашивать по умолчанию, кеды все таки на Qt, а там так принято.

**Comment by suhr** [comment]
> Может он пьяный, в конце концов :) И он это будет делать много раз

Звучит как алкоголизм. Я склонен считать, что люди ошибаются _не настолько_ часто.

(жаль, на десктопных приложениях А/Б тест особо не сделаешь)

**Comment by LLIAKAJL** [comment]
Хотя, пожалуй ты прав. Проверил сейчас Kate, он тоже закрывается без спроса, если ничего не написано.

**Comment by LLIAKAJL** [comment]
Тогда не буду галочку делать, незачем интерфейс перегружать из-за ерунды.

**Comment by LLIAKAJL** [comment]
Вопрос по семантической версии: мажор - это очень серьезные изменения, явно требующие переустановки. Микро - мелкие баги и улучшения, которые не сильно влияют и переустанавливать необязательно. А минор что значит?

**Comment by suhr** [comment]
Новые фичи, которые старая версия не умеет. Но при этом новая версия полностью совместима со старыми фичами и форматами.

Собственно, всё просто: микро — полная совместимость, минор — обратная совместимось, и мажор — совместимость где-то поломана.

**Comment by LLIAKAJL** [comment]
Понятно. Но такая система для Wine Wizard не покатит, наверное. Например, в winetricks появится какой-нибудь хитрый пакет, который потребует изменений в коде, но внешне ничего не поменяется - мажор что-ли делать?

**Comment by suhr** [comment]
Хитрые пакеты, требующие изменений в коде, не каждый день появляются, верно?

**Comment by LLIAKAJL** [comment]
Так-то да, но человек на LOR удивился, что я версию 2 выпустил меньше чем через месяц, а изменения в ней гораздо большие, чем хитрый пакет.

**Comment by suhr** [comment]
Лоропроблемы. Кстати, а как именно хитрый пакет может сломать то, что сейчас есть?

**Comment by LLIAKAJL** [comment]
Например, есть пакеты desktop_mode и videomemorysize. Это переделанные пакеты из winetricks, в нем они не так работают. Я не смог бы их ввести без обновления, так как они получают настройки(разрешение экрана и размер видеопамяти) из программы, переменные в скрипт подставляются. А переменные позиционные, если их будет больше или меньше - они не в те позиции попадут и скрипт сработает не так, как задумано.

**Comment by suhr** [comment]
Однако. А рецепты нельзя обновлять на лету? Запросить с сайта, например.
В конце-концов, отдельная прослойка может брать данные из программы и подставлять в скрипт.

**Comment by LLIAKAJL** [comment]
Рецепты как раз обновляются сами, вот только прога может быть неспособна их принять. Если введу какую-нибудь новую опцию, которую нужно юзеру настроить, откуда скрипты их возьмут, если в старой версии этой опции нет?

**Comment by suhr** [comment]
Один из вариантов — позволить скриптам запрашивать опции через что-то вроде kdialog (только не kdialog) и сохранять их. Если в новой версии появится новая опция, её можно будет перенести в общий конфиг.

В общем, какая-либо гибкость была бы весьма полезна.

**Comment by LLIAKAJL** [comment]
Опять же лишняя зависимость и неродное окошко. Ладно, подумаю над этим, сейчас спать надо идти.
