### ISSUE TITLE
Список приложений?

### ISSUE THREAD

**Issue by spvkgn** [LLIAKAJL/WineWizard#16]
Выполнил `qmake .. & make & winewizard`. Далее должен появиться список доступных приложений для установки или здесь не все готово?

![-control center wine wizard](https://cloud.githubusercontent.com/assets/4147135/19448870/55b00f76-94c5-11e6-8f29-f8b165a9844c.png)

```
~ $ wine --version
wine-1.7.50
```

**Comment by LLIAKAJL** [comment]
Нет, здесь уже установленные приложения появляются: слева - префиксы, справа - ярлыки. Нужно Install жать, там будет список. Кстати, баг на скриншоте приметил - Control должен быть неактивен, когда префиксов нет.

**Comment by spvkgn** [comment]
> Нужно Install жать, там будет список.

При нажатии Install повляется гномовское диалог. окно Select File, списка нет.

**Comment by LLIAKAJL** [comment]
Теперь нужно выбрать установщик приложения, которое поставить хотите, потом и появится список приложений-решений. Или вы думали, что он установщики сам откуда-то скачает? Нет, Wine Wizard по другому работает, он устанавливает зависимости и помогает в настройке, а приложения сами достаете. Чуть позже видеоинструкцию сделаю, там понятно все будет.

**Comment by spvkgn** [comment]
Понятно, спасибо.
