### ISSUE TITLE
Ошибка компиляции

### ISSUE THREAD

**Issue by uentity** [LLIAKAJL/WineWizard#2]
`../src/packagemodel.cpp: В функции-члене «virtual QMimeData* PackageModel::mimeData(const QModelIndexList&) const»:
../src/packagemodel.cpp:126:23: ошибка: переменная «QDataStream stream» инициализирована, хотя имеет неполный тип
     QDataStream stream(&encodedData, QIODevice::WriteOnly);
                       ^
../src/packagemodel.cpp: В функции-члене «virtual bool PackageModel::dropMimeData(const QMimeData*, Qt::DropAction, int, int, const QModelIndex&)»:
../src/packagemodel.cpp:157:23: ошибка: переменная «QDataStream stream» инициализирована, хотя имеет неполный тип
     QDataStream stream(&encodedData, QIODevice::ReadOnly);
                       ^
Makefile:859: ошибка выполнения рецепта для цели «packagemodel.o»
make: *** [packagemodel.o] Ошибка 1
`
В сорцы лезть разбираться не стал, надеюсь вы сможете быстро поправить.
GCC 5.3.1, Qt 5.6, Fedora 23.

**Comment by altelan** [comment]
В packagemodel.h добавь `#include <QDataStream>`

**Comment by LLIAKAJL** [comment]
Исправил
