### ISSUE TITLE
Need good REAME

### ISSUE THREAD

**Issue by Kakadu** [LLIAKAJL/WineWizard#3]
Can you fully describe why this app better than PlayOnLinux and others? Which issues are solved in it and which were introduced. In which cases your app will be more helpful ? Maybe copy-paste from your posts on linux.org.ru forum?

**Comment by LLIAKAJL** [comment]
Yes, i will do it in the near future.

**Comment by stanriff** [comment]
Makefile:498: error processing recipe for aim  «aboutdialog.o»  
What can I do with this error?

**Comment by suhr** [comment]
Close?
