### ISSUE TITLE
No Icon set

### ISSUE THREAD

**Issue by erbauer** [LLIAKAJL/WineWizard#5]
Система:
Debian jessie 8.4
Kernel 3.16.0-4-amd64
MATE 1.8.1

При запуске от пользователя ничего не происходит, в консоле просто мигает курсор, по ^C+c появляется промт.
При запуске через sudo:
`QSystemTrayIcon::setVisible: No Icon set

QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"`
иногда только первая строка.

Думаю проблема на моей стороне, если подскажите как исправить буду очень благодарен.

**Comment by LLIAKAJL** [comment]
Через sudo точно запускать не надо. У вас трей работает? Там иконка должна появиться.

**Comment by erbauer** [comment]
Трей работает. Иконка не появляется. Virtual maneger иконку рисует, Teamviwer иконку рисует (он в своем wine префиксе запускается), VLC рисует (он вроде бы на Qt написан, не уверен). При компиляции были ворнинги. Завтра перекомпелирую, скину вывод.

**Comment by LLIAKAJL** [comment]
Да, вывод нужен, особенно ворнинги. Попробую предположить, что может быть. VLC на Qt, но 4 версии, Wine Wizard на пятой. Вот тут: https://www.linux.org.ru/forum/development/9607369 у людей проблемы с треем Qt5, может аналогично? Попробуйте ее со значка запустить несколько раз, если меню не появится, перед компиляцией в файле wizard.cpp закомментируйте вот эти строки - "if (!QSystemTrayIcon::isSystemTrayAvailable())" и "if (QSystemTrayIcon::isSystemTrayAvailable())" - перекомпилируйте, потом пару раз запустите. Если не поможет, будем думать дальше.

**Comment by LLIAKAJL** [comment]
И да, посмотрите в процессах, нет ли его там, перед перекомпиляцией и запуском.

**Comment by erbauer** [comment]
Если закомментировать эти строки, появляется меню около указателя мыши. Но как его вызвать еще раз не понятно. Кстати, если в нем выбрать "выход", то после вопроса о выходе процес не завершается, приходится убивать руками.

**Comment by erbauer** [comment]
Помог запуск через strace, как советовали здесь https://www.linux.org.ru/forum/desktop/11170308.
Выход тоже заработал нормально. Может быть добавить в коде задержку перед рисование иконки, но я не силен в cpp.
Кстати, Dropbox рисует иконку нормально.

**Comment by LLIAKAJL** [comment]
Значит, трей он все-таки находит, но не хочет выводить туда. Задержку можно добавить, надо поразбираться.

**Comment by LLIAKAJL** [comment]
Я сразу подозревал, что баги с треем могут быть, слышал о них уже. Вот эти строки - if (QSystemTrayIcon::isSystemTrayAvailable()) - должны не давать показаться в трее, если его нет, и тогда можно было бы меню со значка вызывать, но баг оказался сложнее.

**Comment by erbauer** [comment]
Я думаю, что трей доступен, по тому что при запуске  его содержимое дергается на несколько пикселей и сразу возвращается назад, как будто пытается выделить место под иконку. Может надежнее при запуске выводить окно, а потом сворачивать его в трей, или дать возможность просто свернуть в панель задач?

**Comment by LLIAKAJL** [comment]
Проблема в том, что никакого окна, собственно, и нет. В трее меню с ярлыками установленных приложений висит. Окно с выбором решения при установке появляется, если из меню выбрать "Install Application" или exe/msi двойным щелчком запустить.

**Comment by LLIAKAJL** [comment]
В общем, сделал так: по умолчанию трей выключен, программа завершается автоматически, если ничего не запущено. Трей и автоматическое завершение можно включать/выключать в меню. Можете поместить значок на панель и запускать как "Пуск" в винде.
